name: Daily Social Media ETL

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM UTC
  workflow_dispatch:  # Manual trigger option

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install pandas requests boto3

      - name: Run pipeline
        run: |
          python run_pipeline.py

      - name: Configure Git for Actions
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Commit and push CSV
        run: |
          git add unified_posts_transformed.csv
          git commit -m "Update CSV from GitHub Actions run $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/MuhamedHisham/social-media-etl.git HEAD:main
